require("barbecue").setup({
    exclude_filetypes = { "NvimTree" },
    theme = {
        normal = { fg = "#c4a089" }, -- Warm beige
        ellipsis = { fg = "#8a6542" }, -- Dark brown
        separator = { fg = "#8a6542" },
        modified = { fg = "#8a6542" },
        dirname = { fg = "#8a6542" },
        basename = { bold = true },
        context = {},
        context_file = { fg = "#b58900" }, -- Golden brown
        context_module = { fg = "#b58900" },
        context_namespace = { fg = "#b58900" },
        context_package = { fg = "#b58900" },
        context_class = { fg = "#b58900" },
        context_method = { fg = "#b58900" },
        context_property = { fg = "#b58900" },
        context_field = { fg = "#b58900" },
        context_constructor = { fg = "#b58900" },
        context_enum = { fg = "#b58900" },
        context_interface = { fg = "#b58900" },
        context_function = { fg = "#b58900" },
        context_variable = { fg = "#b58900" },
        context_constant = { fg = "#b58900" },
        context_string = { fg = "#b58900" },
        context_number = { fg = "#b58900" },
        context_boolean = { fg = "#b58900" },
        context_array = { fg = "#b58900" },
        context_object = { fg = "#b58900" },
        context_key = { fg = "#b58900" },
        context_null = { fg = "#b58900" },
        context_enum_member = { fg = "#b58900" },
        context_struct = { fg = "#b58900" },
        context_event = { fg = "#b58900" },
        context_operator = { fg = "#b58900" },
        context_type_parameter = { fg = "#b58900" },
    },
})
